service: rds-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: dist/main.handler
    environment:
      db_user: ${file(./dbconfig.yml):db_user}
      db_host: ${file(./dbconfig.yml):db_host}
      db_database: ${file(./dbconfig.yml):db_database}
      db_password: ${file(./dbconfig.yml):db_password}
      db_port: ${file(./dbconfig.yml):db_port}
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      - http:
          method: get
          path: '/test'
